import {
  ArrowDownIcon,
  ChatBubbleIcon,
  DiscordLogoIcon,
  FaceIcon,
  Half2Icon,
  MagicWandIcon,
  PauseIcon,
  PlayIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  SlashIcon,
  DividerHorizontalIcon,
  DividerVerticalIcon,
  ChevronDownIcon,
  InputIcon,
  TextIcon,
  LoopIcon,
  ColumnsIcon,
  GlobeIcon,
  CounterClockwiseClockIcon,
  DotFilledIcon
} from '@radix-ui/react-icons'

import {
  ListTreeIcon,
  ALargeSmall,
  Wrench,
  AlignLeft,
  ArrowBigDownDash,
  ArrowBigUpDash,
  ArrowDown,
  ArrowLeft,
  BrainCircuit,
  ArrowRight,
  ArrowUpDown,
  BookOpen,
  Building2,
  Calendar,
  CalendarDays,
  ChartColumnIncreasing,
  Check,
  CheckCircle2,
  CheckIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  CircleX,
  Clock,
  Presentation,
  Copy,
  CornerDownRight,
  CreditCard,
  Database,
  Delete,
  Dot,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  FileAudio,
  ClipboardList,
  FileText,
  FileType2,
  FileVideo,
  Globe,
  Group,
  Hammer,
  Headphones,
  IdCard,
  Info,
  Key,
  KeyRound,
  Layers,
  Loader2,
  LoaderCircle,
  LogOut,
  Mail,
  MessageCircleMore,
  MessagesSquare,
  Minus,
  Moon,
  MoreVertical,
  PaperclipIcon,
  Pen,
  Play,
  Plus,
  RefreshCcw,
  Rocket,
  ScanText,
  Search,
  Send,
  Settings2,
  ShieldCheck,
  Smile,
  Sun,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash2,
  User,
  Users,
  X,
  User2,
  Volume2,
  VolumeX,
  AppWindow,
  EllipsisVertical,
  ArrowDownNarrowWide,
  ArrowDownWideNarrow,
  ArrowDownAZ,
  ArrowDownZA,
  Settings,
  Radio,
  ChevronsUpDown,
  ChartLine,
  Tags,
  Home,
  ListStartIcon,
  WorkflowIcon,
  LucideChevronDown,
  EyeOff,
  WifiOffIcon,
  FileSpreadsheet,
  FileJson,
  FolderOpen,
  Maximize2,
  Edit3,
  BoxIcon,
  MemoryStickIcon,
  AlignLeftIcon,
  ArrowUpRight,
  Monitor,
  XIcon,
  ArrowUpNarrowWide,
  PlusIcon,
  Text,
  LinkIcon,
  File,
  Book,
  GraduationCap,
  AlertTriangle,
  SplitIcon,
  NetworkIcon,
  ReplaceIcon,
  CopyPlusIcon,
  PanelRightOpen,
  Laptop,
  FunctionSquare,
  SquareFunctionIcon,
  ArrowUp,
  Expand,
  AppWindowIcon,
  SearchCheckIcon,
  StopCircleIcon,
  Braces,
  ListEndIcon,
  ArrowUpFromDot,
  Loader
} from 'lucide-react'

import {
  ActiveSidebarIcon,
  Agent,
  AnthropicLogo,
  Avatar,
  AwsLogo,
  AzureLogo,
  ChatBubble,
  CohereLogo,
  Context,
  DashboardIcon,
  DeepseekLogo,
  DragIcon,
  FireworksLogo,
  GeminiLogo,
  GitHubIcon,
  GoogleIcon,
  GroqLogo,
  MistralLogo,
  OllamaLogo,
  OpenAILogo,
  Pencil,
  RadioButton,
  ReasoningIcon,
  ReloadIcon,
  ScanFace,
  SheetIcon,
  SystemIcon,
  ToolIcon,
  UserFace,
  XaiLogo,
  TeamOrangeBgIcon,
  HuggingFaceIcon,
  PerplexityIcon,
  NvidiaIcon,
  OpenRouterIcon,
  SambanovaIcon,
  LiteLLMIcon,
  TogetherAIIcon,
  IBMIcon,
  LMStudioIcon,
  WorkflowBlankStateVisual,
  TeamBlankStateVisual,
  AppBlankStateVisual,
  AgentBlankStateVisual,
  EvalsBlankStateIcon,
  ReturnIcon,
  MemoryBlankStateVisual,
  Brain,
  Whatsapp,
  OsBlankStateIcon,
  Slack,
  WorkflowWithOrangeBg,
  KnowledgeBlankStateIcon,
  WorkflowOrangeBgIcon,
  BrainCircuit2,
  TracesBlankStateVisual
} from './custom-icons'
import { type IconTypeMap } from './types'
import {
  NoLoggedSessionIcon,
  TeamLogoIcon
} from '@/components/pages/SessionsPage/BlankState/NotLoggedSession/NoLoggedSession'

export const ICONS: IconTypeMap = {
  run: Play,
  GitHub: GitHubIcon,
  Google: GoogleIcon,
  dashboard: DashboardIcon,
  'list-tree': ListTreeIcon,
  datasets: Layers,
  playground: ChatBubble,
  settings: Settings2,
  legal: FileText,
  Discord: DiscordLogoIcon,
  documentation: BookOpen,
  time: Clock,
  reload: ReloadIcon,
  show: ToggleRight,
  hide: ToggleLeft,
  viewMode: ALargeSmall,
  details: AlignLeft,
  evaluation: ClipboardList,
  prompt: MessageCircleMore,
  'human-review': ScanText,
  empty: CircleX,
  instructions: CircleHelp,
  'caret-left': ChevronLeft,
  'caret-right': ChevronRight,
  'caret-down': ChevronDown,
  'caret-up': ChevronUp,
  'eye-closed': EyeOff,
  'eye-open': Eye,
  copy: Copy,
  activeSidebar: ActiveSidebarIcon,
  avatar: Avatar,
  'scan-face': ScanFace,
  loader: LoaderCircle,
  sort: ArrowUpDown,
  'user-face': UserFace,
  'radio-button': RadioButton,
  api: KeyRound,
  'arrow-up-right': ArrowUpRight,
  close: X,
  check: Check,
  billingCycle: RefreshCcw,
  refresh: RefreshCcw,
  support: Mail,
  downgrade: ArrowDown,
  data: Database,
  calendar: Calendar,
  user: User,
  users: Users,
  workspace: Building2,
  error: CircleAlert,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  read: Eye,
  write: Pen,
  admin: ShieldCheck,
  delete: Delete,
  userInfo: IdCard,
  name: MessageCircleMore,
  billing: CreditCard,
  create: Plus,
  ellipsisHorizontal: Ellipsis,
  permission: Key,
  review: Search,
  rocket: Rocket,
  trash: Trash2,
  globe: Globe,
  'triangle-left': TriangleLeftIcon,
  'triangle-right': TriangleRightIcon,
  'triangle-down': TriangleDownIcon,
  'triangle-up': TriangleUpIcon,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  half2: Half2Icon,
  tool: ToolIcon,
  system: SystemIcon,
  dot: Dot,
  send: Send,
  'arrow-right': ArrowRight,
  'user-2': User2,
  info: Info,
  'more-vertical': MoreVertical,
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  'arrow-big-down-dash': ArrowBigDownDash,
  'arrow-big-up-dash': ArrowBigUpDash,
  'bar-chart-4': ChartColumnIncreasing,
  hammer: Hammer,
  'arrow-down': ArrowDownIcon,
  'external-link': ExternalLink,
  pencil: Pencil,
  face: FaceIcon,
  smile: Smile,
  'magic-wand': MagicWandIcon,
  agent: Agent,
  'wifi-off': WifiOffIcon,
  'messages-square': MessagesSquare,
  reasoning: ReasoningIcon,
  drag: DragIcon,
  'chat-bubble': ChatBubbleIcon,
  'arrow-left': ArrowLeft,
  sheet: SheetIcon,
  'calendar-days': CalendarDays,
  context: Context,
  search: Search,
  'check-circle-2': CheckCircle2,
  workflow: WorkflowIcon,
  'chevron-down': ChevronDownIcon,
  'corner-down-right': CornerDownRight,
  download: Download,
  paperclip: PaperclipIcon,
  'file-type-2': FileType2,
  'file-audio': FileAudio,
  'file-video': FileVideo,
  headphones: Headphones,
  play: PlayIcon,
  pause: PauseIcon,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'loader-2': Loader2,
  'check-icon': CheckIcon,
  app: AppWindow,
  'ellipsis-vertical': EllipsisVertical,
  'arrow-down-narrow-wide': ArrowDownNarrowWide,
  'arrow-up-right-narrow-wide': ArrowUpNarrowWide,
  'arrow-down-wide-narrow': ArrowDownWideNarrow,
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-down-z-a': ArrowDownZA,
  'settings-2': Settings,
  radio: Radio,
  team: Group,
  'chevron-up-down': ChevronsUpDown,
  slash: SlashIcon,
  'chart-line': ChartLine,
  default: Building2,
  'team-orange-bg': TeamOrangeBgIcon,
  maximize: Maximize2,
  tags: Tags,
  'divider-horizontal': DividerHorizontalIcon,
  'divider-vertical': DividerVerticalIcon,
  home: Home,
  cross: XIcon,
  'hugging-face': HuggingFaceIcon,
  perplexity: PerplexityIcon,
  nvidia: NvidiaIcon,
  'open-router': OpenRouterIcon,
  sambanova: SambanovaIcon,
  'lite-llm': LiteLLMIcon,
  together: TogetherAIIcon,
  ibm: IBMIcon,
  lmstudio: LMStudioIcon,
  'team-blank-state-visual': TeamBlankStateVisual,
  'workflow-blank-state-visual': WorkflowBlankStateVisual,
  'app-blank-state-visual': AppBlankStateVisual,
  'agent-blank-state-visual': AgentBlankStateVisual,
  'eval-blank-state-icon': EvalsBlankStateIcon,
  'knowledge-blank-state-icon': KnowledgeBlankStateIcon,
  'eval-chevron-down': LucideChevronDown,
  'session-agent-blank-state-icon': NoLoggedSessionIcon,
  'session-team-blank-state-icon': TeamLogoIcon,
  csv: FileSpreadsheet,
  json: FileJson,
  edit: Edit3,
  return: ReturnIcon,
  minus: Minus,
  box: BoxIcon,
  'brain-circuit': BrainCircuit,
  'memory-stick': MemoryStickIcon,
  'align-left': AlignLeftIcon,
  'memory-blank-state-visual': MemoryBlankStateVisual,
  brain: Brain,
  monitor: Monitor,
  whatsapp: Whatsapp,
  slack: Slack,
  plus: PlusIcon,
  textLogo: TextIcon,
  text: Text,
  input: InputIcon,
  presentation: Presentation,
  link: LinkIcon,
  'folder-open': FolderOpen,
  file: File,
  book: Book,
  wrench: Wrench,
  'graduation-cap': GraduationCap,
  'alert-triangle': AlertTriangle,
  'os-blank-state-icon': OsBlankStateIcon,
  split: SplitIcon,
  network: NetworkIcon,
  replace: ReplaceIcon,
  loop: LoopIcon,
  'workflow-steps': ListStartIcon,
  'copy-plus': CopyPlusIcon,
  'panel-right-open': PanelRightOpen,
  'function-square': FunctionSquare,
  columns: ColumnsIcon,
  'square-function': SquareFunctionIcon,
  laptop: Laptop,
  'globe-2': GlobeIcon,
  'workflow-with-orange-bg': WorkflowWithOrangeBg,
  'arrow-up': ArrowUp,
  expand: Expand,
  'app-window': AppWindowIcon,
  'dot-filled': DotFilledIcon,
  'search-check': SearchCheckIcon,
  stop: StopCircleIcon,
  'workflow-orange-bg': WorkflowOrangeBgIcon,
  braces: Braces,
  'counter-clockwise-clock': CounterClockwiseClockIcon,
  'list-end': ListEndIcon,
  'brain-circuit-2': BrainCircuit2,
  'arrow-up-from-dot': ArrowUpFromDot,
  'working-loader': Loader,
  'traces-blank-state-visual': TracesBlankStateVisual
}
